version: '2'
services:
  app:
    image: localstack_ruby_client_development_app
    container_name: localstack_ruby_client_development_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    command:
      /sbin/my_init
    volumes:
      - ./:/opt/localstack_ruby_client
    links:
      - localstack
  localstack:
    environment:
      - SERVICES=s3,dynamodb,sqs
    image: localstack/localstack
    container_name: localstack_ruby_client_development_localstack
